# Generated by Django 5.0 on 2024-09-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='izr_staff.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('staff', 'Vorstand'), ('manager', 'Vertretung'), ('admin_schulunterricht', 'Schulunterricht'), ('admin_frauen', 'Frauen'), ('admin_entwicklung', 'Entwicklung'), ('admin_familien_kinder', 'Familien & Kinder'), ('admin_bestattungen', 'Islamische Bestattungen'), ('admin_gebaudehalter', 'Gebäudehalter'), ('admin_hausverwaltung', 'Hausverwaltung'), ('admin_sport_jugend', 'Sport & Jugend')], max_length=50, verbose_name='Role'),
        ),
    ]
