# Generated by Django 5.0 on 2024-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_school', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
