# Generated by Django 5.0 on 2024-09-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ar', models.CharField(max_length=255)),
                ('data_de', models.CharField(max_length=255)),
                ('hadith_ar', models.TextField()),
                ('hadith_de', models.TextField()),
            ],
        ),
    ]
