# Generated by Django 5.0 on 2024-09-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0002_hadith'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=50)),
                ('token', models.TextField()),
                ('test2', models.BooleanField(default=False)),
            ],
        ),
    ]
