# Generated by Django 5.0 on 2024-09-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0003_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('asr', models.IntegerField(default=15)),
                ('dhuhr', models.IntegerField(default=15)),
                ('fajr', models.IntegerField(default=15)),
                ('isha', models.IntegerField(default=5)),
                ('jumaa', models.IntegerField(default=0)),
                ('maghrib', models.IntegerField(default=5)),
                ('tarawih', models.IntegerField(default=0)),
                ('day_correction', models.IntegerField(default=1)),
                ('ramadan', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=3)),
            ],
            options={
                'verbose_name': 'Prayer Config',
                'verbose_name_plural': 'Prayer Configurations',
            },
        ),
    ]
