# Generated by Django 5.0 on 2024-09-28 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0005_event_description_event_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerCalculationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_angle', models.FloatField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(18)])),
                ('calculation_method', models.IntegerField(choices=[(1, 'Muslim World League'), (2, 'Islamic Society of North America'), (3, 'Egyptian General Authority of Survey'), (4, 'Umm al-Qura University, Makkah'), (5, 'University of Islamic Sciences, Karachi'), (6, 'Custom Method')])),
                ('default_longitude', models.FloatField()),
                ('default_latitude', models.FloatField()),
            ],
        ),
    ]
