# Generated by Django 5.0 on 2024-09-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0006_prayercalculationconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayercalculationconfig',
            options={'verbose_name': 'Prayer Calculation Configuration', 'verbose_name_plural': 'Prayer Calculation Configuration'},
        ),
    ]
