# Generated by Django 5.0 on 2024-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0010_blog_remove_blogparagraph_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Max Mustermann', max_length=200),
            preserve_default=False,
        ),
    ]
