# Generated by Django 5.0 on 2024-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0011_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
