# Generated by Django 5.0 on 2024-10-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0012_event_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='izr_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
