# Generated by Django 5.0 on 2024-10-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0014_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='v_image',
            field=models.BooleanField(default=False, verbose_name='Vertical Image'),
        ),
    ]
