# Generated by Django 5.0 on 2024-10-05 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0015_contentitem_v_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Gallery Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Gallery Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/', verbose_name='Upload Image')),
                ('is_vertical', models.BooleanField(default=True, verbose_name='Is Vertical')),
                ('orientation', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], max_length=10, verbose_name='Orientation')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='izr_media.gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
