# Generated by Django 5.0 on 2024-10-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izr_media', '0016_gallery_galleryimage_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='orientation',
        ),
    ]
