# Generated by Django 5.0 on 2024-10-06 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('blog', 'Blog'), ('project', 'Project')], default='blog', max_length=50)),
                ('language', models.CharField(choices=[('en', 'EN'), ('de', 'DE')], default='de', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Imprint Deutsch', max_length=255, verbose_name='Title')),
                ('angaben_gem_tmg', models.TextField(verbose_name='Angaben gem. § 5 TMG')),
                ('kontaktaufnahme', models.TextField(verbose_name='Kontaktaufnahme')),
                ('haftung_inhalte', models.TextField(verbose_name='Haftung für Inhalte')),
                ('haftung_externe_links', models.TextField(verbose_name='Haftungsbeschränkung für externe Links')),
                ('urheberrecht', models.TextField(verbose_name='Urheberrecht')),
                ('widerrufsrecht', models.TextField(verbose_name='Widerrufsrecht')),
                ('folgen_widerruf', models.TextField(verbose_name='Folgen des Widerrufs')),
                ('ausschluss_erloeschensgruende', models.TextField(verbose_name='Ausschluss- bzw. Erlöschensgründe')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='LastProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='product_photos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amazon_link', models.URLField(max_length=500)),
                ('poem', models.TextField()),
            ],
            options={
                'verbose_name': 'Last Product',
                'verbose_name_plural': 'Last Product',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('book_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Home Page Poem',
                'verbose_name_plural': 'Home Page Poem',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='product_photos/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amazon_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(choices=[('header', 'Header'), ('paragraph', 'Paragraph'), ('image', 'Image')], max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('v_image', models.BooleanField(default=False, verbose_name='Vertical Image')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='izr_products.blog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
