# Generated by Django 5.0 on 2024-10-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('en', 'EN'), ('de', 'DE')], default='de', max_length=50),
        ),
    ]
