# Generated by Django 5.0 on 2024-10-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_products', '0002_product_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
