# Generated by Django 5.0 on 2024-10-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izr_products', '0003_alter_product_options_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
    ]
