# Generated by Django 5.0 on 2024-10-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_products', '0004_alter_product_options_remove_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Hero Image')),
            ],
        ),
    ]
