# Generated by Django 5.0 on 2024-10-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_products', '0005_heroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='poem',
            name='language',
            field=models.CharField(choices=[('en', 'EN'), ('de', 'DE')], default='de', max_length=50),
        ),
    ]
