# Generated by Django 5.0 on 2024-10-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izr_products', '0006_message_poem_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastproduct',
            name='language',
            field=models.CharField(choices=[('en', 'EN'), ('de', 'DE')], default='de', max_length=50),
        ),
    ]
